Implement Next.js version of the Typescript challenge
wieni/wm-typescript-challenge pull request #5
Opened 2024-08-05 07:55 UTC by VincentRavoetWieni

2025-01-30 14:55 UTC, wietswieni requested changes

2025-01-30 14:55 UTC, wietswieni commented on v2/solution/.next/app-build-manifest.json
> +{
@VincentRavoetWieni 
- Alle changes in /v2/ mogen verhuizen naar de originele folder. De originele challenge mag dus overschreven worden
- `.next` folder mag in .gitignore, maar ik denk dat dit al opgelost gaat zijn door puntje 1 aan te passen

2025-01-30 14:55 UTC, wietswieni commented on v2/solution/.next/app-build-manifest.json
> +  "pages": {
@VincentRavoetWieni 

/v2/solution -> De solution folder is goed om achter de hand te houden, maar mag uit de repo verwijderd worden omdat we die ook gaan sharen met sollicitanten

2025-01-30 14:55 UTC, wietswieni commented on .nvmrc
> -v18.2.0
Kleintje, maar mag gewoon `18` worden, zonder minder / patch version. Dan trekken we dat gelijk met onze andere projecten

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/README.md
> +# Getting Started with this project
@vincent het is niet nodig om een extra `/v2` folder aan te maken in de root. Je mag deze files gewoon overschrijven, dan kan ik de changes ook makkelijker zien in deze PR

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/README.md
> +# Getting Started with this project
het is niet per sé nodig om een extra `/v2` folder aan te maken in de root. Je mag deze files gewoon overschrijven, dan kan ik de changes ook makkelijker zien in deze PR en werkt de gitignore ook weer

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/README.md
> +# Getting Started with this project
@VincentRavoetWieni het is niet per sé nodig om een extra `/v2` folder aan te maken in de root. Je mag deze files gewoon overschrijven, dan kan ik de changes ook makkelijker zien in deze PR en werkt de gitignore ook weer

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/user-stories/not-found.md
> +- Make sure the error and the button to go back show in the middle of the screen.
Dit lijntje mag er nog uit, we vinden het altijd interessant om kandidaten te challengen en ze zelf iets te laten bedenken

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/user-stories/popular.md
> +- You can just assume that the first five from the `app/api/cocktails/cocktails.json` file are the most popular. Just slice the first 5 from the returned array result.
Dit lijntje mag er nog uit, we vinden het altijd interessant om kandidaten te challengen en ze zelf iets te laten bedenken

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/user-stories/props.md
> +- I can see the garnish and glass properties also show up in this component. You can decide what this will look like.
Hier ook nog iets te gedetailleerd uitgeschreven. We willen kandidaten echt laten zoeken naar een oplossing, en eventuele zaken zoals `garnish` en `glass` zelf vinden in de json en weergeven in de front-end

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/user-stories/search.md
> +As a user
Mag nog op één lijn #ocd

2025-01-30 14:55 UTC, wietswieni commented on v2/wm-typescript-challenge/user-stories/search.md
> +- I can see a nicely styled search input field on the recipes page that I can use to filter the list of cocktails based on their name.
Toevoegen
- Debounce toevoegen
- Aanmoedigen van libraries zoals React Query
- Eventueel teasen met extra's zoals: autocompletion, autohints, suggestions, ... De lat mag hoog liggen 😎

2025-01-30 14:59 UTC, wietswieni commented
@VincentRavoetWieni review = done. Ik heb `/v2/solution` wel in gitignore gestoken, aangezien we de repo ook gaan delen met kandidaten

2025-01-30 21:32 UTC, VincentRavoetWieni commented on .nvmrc
> -v18.2.0
Next 14 heeft wel `>= 18.17.0` nodig:

![Scherm­afbeelding 2025-01-30 om 22 32 00](https://github.com/user-attachments/assets/7322e6b9-5de5-4f5f-8a56-5a5bd6801621)

2025-01-31 15:11 UTC, VincentRavoetWieni commented
@wietswieni 

Voila 🌈

2025-02-03 13:21 UTC, JodusNodus commented
Omdat er momenteel nog geen backend werk in zat, hebben we besloten om bonus criteria toe te voegen op de search story. Als ze zich gemotiveerd voelen kunnen ze een extra API endpoint maken om de search server side te doen met een fuzzy search library.
Staat in aparte PR naar deze branch #6 .

2025-02-03 15:48 UTC, wietswieni approved these changes

2025-02-03 15:50 UTC, merged